exporter:
  fields:
    pas:
      default: 15
      selector:
        select:
          options:
            - "5"
            - "15"
            - "60"
    debut:
      selector:
        date:
    fin:
      selector:
        date:
envoyer:
reimporter:
  fields:
    debut:
      required: true
      selector:
        date:
    fin:
      required: true
      selector:
        date:
